<!-- AUTO-GENERATED by tools/gen_agent_rules.py (v0.1.0) — DO NOT EDIT BY HAND.
     진실원본: platform/prompts/global-system.md (+ platform/policies/).
     재생성: python tools/gen_agent_rules.py -->

# ai-autodev-harness — 에이전트 운영 규칙 (강제)

이 저장소는 **모델·하네스 비종속 AI 자동개발 하네스**다. 어떤 AI 에이전트(Claude/Cursor/Gemini/
Copilot/API)든 이 파일을 진입점으로 읽고 아래 규칙을 **반드시** 따른다.
규칙 위반 산출물은 pre-commit / CI 훅(`tools/validate_node.py`)이 거부한다.

## 0. 이 프로젝트가 무엇인가
- `projects/<name>-node/repo/` = 실제 소프트웨어 코드(symlink/clone/submodule).
- `projects/<name>-node/`(repo 제외) = 그 프로젝트의 **AI 운영 데이터**(context/scenario/history/info/code 규칙).
- 플랫폼 루트 = 글로벌 AI 설정(`platform/`), 변환 도구(`tools/`), 기판 노출(`mcp/`), 어댑터(`adapters/`).
- 사용법: `docs/USAGE.md` · 설계: `docs/ARCHITECTURE.md` · 학습: `docs/learning/harness-curriculum.md`.

## 1. 공통 규칙 (필수)
1. 작업 시작 전 대상 프로젝트의 `history/ONBOARDING.md`를 읽는다.
2. 코드 작성은 `code/coding_convention/`을 먼저 읽고 plan → verify → implement.
3. 위험 행동은 `platform/policies/approval-gates.md`의 게이트를 통과한다.
4. 사실/데이터는 `info/`에서 가져오고, 출처는 `info/index.yaml`로 확인·인용한다.
5. 비자명한 결정은 `history/adr/`에, 진행 경과는 `history/worklog/<티켓>.md`에 기록한다.
6. 시크릿은 이름으로만 참조한다(`platform/policies/secrets.md`).

## 2. 파일 배치 (강제)
- `repo/` 안에는 AI 파일(프롬프트/컨텍스트/이력/info)을 **절대** 두지 않는다 — 전부 `-node/` 레벨에.
- 데이터는 `data/update/`에 투입 → `harness ingest <node>`(또는 어댑터의 `/update`)로
  `info/`(md/SQL/vector)로 변환. 원본은 `archives/`, 출처·해시는 `info/index.yaml`.
- 변환기는 `tools/data-to-info/`에 두고 `tools/README.md` 규칙을 따른다.

## 3. 작업 진입 절차
1) 노드 `history/ONBOARDING.md` 읽기 → 2) `code/coding_convention/` 읽기 →
3) plan → verify → implement → 4) 경과를 `history/worklog/<티켓>.md`에 기록 →
5) 위험행동(ssh/scp/push/deploy/삭제)은 `platform/policies/approval-gates.md` 게이트 통과.

## 4. 검증 (커밋 전 필수)
`python tools/validate_node.py <node>` 통과해야 한다(pre-commit 훅이 자동 실행, CI에서도 검사).
직접 파일쓰기는 허용되나, 규칙 위반은 훅이 사후 거부한다.
