#!/usr/bin/env python3
"""gen_agent_rules — 단일 진실원본에서 플랫폼별 '진입 규칙 파일'을 생성.

강제성 ① 보편층(모델·하네스 비종속): 어떤 AI 에이전트(Claude/Cursor/Gemini/Copilot/API)든
자기 하네스가 자동 로드하는 파일을 통해 동일 규칙을 주입받는다.

진실원본: platform/prompts/global-system.md (+ platform/policies/).
정본 `AGENTS.md`(벤더 무관 표준)만 추적한다. 특정 하네스용 진입 파일은 `platform/harnesses.yaml`의
`enabled` 에 켠 하네스에 한해, 그 하네스의 `rules_file` 이름으로 **정본을 가리키는 심볼릭 링크**를
로컬 생성한다(미추적, `.gitignore`). 심링크 미지원 OS(Windows 등)는 자동 복제 폴백.
→ 아무 하네스도 안 켜면 AGENTS.md 만 생성(순수 중립). 새 하네스 = harnesses.yaml 에 블록 추가.

사용:
  python tools/gen_agent_rules.py            # 플랫폼 루트
  python tools/gen_agent_rules.py --node my_proj   # 노드 레벨
정본은 AUTO-GENERATED 헤더가 붙으며 재생성으로 덮어쓴다(수동 편집 금지).
"""
from __future__ import annotations
import argparse, os, shutil, sys

__tool_version__ = "0.3.0"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # tools/ 의 부모
sys.path.insert(0, os.path.join(ROOT, "tools", "lib"))
import registry  # platform/harnesses.yaml (활성 하네스만)

CANONICAL = "AGENTS.md"   # 유일 추적 정본(벤더 무관). 하네스별 진입 파일명은 레지스트리에서 읽음.

HEADER = (
    "<!-- AUTO-GENERATED by tools/gen_agent_rules.py (v%s) — DO NOT EDIT BY HAND.\n"
    "     진실원본: platform/prompts/global-system.md (+ platform/policies/).\n"
    "     재생성: python tools/gen_agent_rules.py%s -->\n"
)


def _global_rules() -> str:
    """global-system.md 본문(헤더 제외 규칙들)을 추출."""
    p = os.path.join(ROOT, "platform", "prompts", "global-system.md")
    if not os.path.exists(p):
        return "(platform/prompts/global-system.md 없음 — 먼저 작성하세요.)"
    lines = open(p, encoding="utf-8").read().splitlines()
    # frontmatter(---...---) 와 첫 H1 제거 후 본문만
    body, in_fm, seen_h1 = [], False, False
    for ln in lines:
        if ln.strip() == "---":
            in_fm = not in_fm; continue
        if in_fm:
            continue
        if not seen_h1 and ln.startswith("# "):
            seen_h1 = True; continue
        body.append(ln)
    return "\n".join(body).strip()


def _platform_body() -> str:
    rules = _global_rules()
    return f"""# ai-autodev-harness — 에이전트 운영 규칙 (강제)

이 저장소는 **모델·하네스 비종속 AI 자동개발 하네스**다. 어떤 AI 에이전트/하네스(모델·도구 무관)든
이 파일을 진입점으로 읽고 아래 규칙을 **반드시** 따른다.
규칙 위반 산출물은 pre-commit / CI 훅(`tools/validate_node.py`)이 거부한다.

> 이 `AGENTS.md`가 **유일한 진입 규칙 정본**이다(벤더 무관 표준). 특정 하네스가 요구하는 진입 파일은
> `platform/harnesses.yaml`에서 그 하네스를 켠 뒤 `harness gen-rules`로 이 정본의 심볼릭 링크를 로컬
> 생성한다(미추적). 임의 파일명이 필요하면 `ln -s AGENTS.md <필요한이름>`.

## 0. 이 프로젝트가 무엇인가
- **템플릿 플랫폼**이다. 실제 프로젝트 노드는 들어있지 않고 `projects/_template-node/`(틀)만 있다.
  → 새 노드는 `./harness init <name>` 으로 만든다(`docs/USAGE.md` 참고).
- **준비(부트스트랩):** clone 본은 venv/git훅/진입규칙 심링크/벡터가 비어 있어 1회 준비가 필요하다.
  `./harness <명령>` 첫 실행(또는 MCP 서버 기동) 시 **자동으로 1회 수행**되며, 표식은 `.harness-ready`
  파일이다(있으면 건너뜀). **이 파일이 없고 아직 준비가 안 된 상태라면, 작업을 시작하기 전에
  `make ready`(또는 `bash scripts/ensure_ready.sh`)를 1회 실행하라.** (오프라인: `HARNESS_EMBED_BACKEND=hash make ready`)
- **하네스 주입(동적):** 사용할 AI CLI/IDE에 맞게 `./harness use <claude-code|cursor|gemini|copilot>` 를
  실행하면 그 하네스의 진입규칙 파일(예: `.cursorrules`)·스킬이 로컬 생성된다.
  **유저가 "cursor(혹은 다른 하네스) 쓸게"라고 하면 이 명령을 실행하라.**
- `projects/<name>-node/repo/` = 실제 소프트웨어 코드(symlink/clone/submodule).
- `projects/<name>-node/`(repo 제외) = 그 프로젝트의 **AI 운영 데이터**(context/scenario/history/info/code 규칙).
- 플랫폼 루트 = 글로벌 AI 설정(`platform/`), 변환 도구(`tools/`), 기판 노출(`mcp/`), 어댑터(`adapters/`).
- 사용법: `docs/USAGE.md` · 설계: `docs/ARCHITECTURE.md` · 기여/커밋규칙: `CONTRIBUTING.md`.

## 1. 공통 규칙 (필수)
{rules}

## 2. 파일 배치 (강제)
- `repo/` 안에는 AI 파일(프롬프트/컨텍스트/이력/info)을 **절대** 두지 않는다 — 전부 `-node/` 레벨에.
- 데이터는 `data/update/`에 투입 → `harness ingest <node>`로 `info/`(md/SQL/vector)로 변환.
  원본은 `archives/`, 출처·해시는 `info/index.yaml`.
- 변환기는 `tools/data-to-info/`에 두고 `tools/README.md` 규칙을 따른다.

## 3. 작업 진입 절차
1) 노드 `history/ONBOARDING.md` 읽기 → 2) `code/coding_convention/` 읽기 →
3) plan → verify → implement → 4) 경과를 `history/worklog/<티켓>.md`에 기록 →
5) 위험행동(ssh/scp/push/deploy/삭제)은 `platform/policies/approval-gates.md` 게이트 통과.

> **이력 자동 인계:** `history/ONBOARDING.md`는 worklog·ADR·**repo 커밋**·**verify 테스트 결과**를
> 모아 자동 생성되는 큐레이션 인계서다. MCP `begin_session` 이 이를 반환하고, `append_worklog`/
> `record_decision`/`ingest`/`harness verify`/`onboard` 시 자동 갱신된다. **새 에이전트는 이걸로 이전
> 이력을 인계받으므로, 너의 진행 경과(`append_worklog`)·결정(`record_decision`)을 반드시 남겨라 —
> 안 남기면 다음 에이전트가 못 본다.**

## 4. 검증 (커밋 전 필수)
`python tools/validate_node.py <node>` 통과해야 한다(pre-commit 훅이 자동 실행, CI에서도 검사).
직접 파일쓰기는 허용되나, 규칙 위반은 훅이 사후 거부한다.

## 5. 운영 플레이북 (자연어 요청 → 플랫폼 명령)
유저는 명령을 직접 치기보다 **너에게 자연어로 요청**한다. 아래 요청은 **반드시 이 플랫폼 명령/도구로
수행**하라(임의 우회·수작업 금지). 어떤 하네스에서 돌든 동일하게 따른다. 모르면 `./harness -h`.

| 유저가 이렇게 말하면 | 너는 이렇게 한다 |
|---|---|
| "<경로>의 프로젝트 붙여줘/추가해줘" | `./harness init <name> --link-type symlink --target <절대경로>` → `./harness bootstrap projects/<name>-node` |
| "cursor/gemini/copilot 쓸게" | `./harness use <harness>` (진입규칙·스킬 로컬 생성) |
| "bitbucket/jira/figma MCP 붙여줘" | `platform/mcp-servers.yaml` 의 `enabled` 에 해당 서버 추가(없으면 `servers:` 에 정의; **레지스트리엔 `${{ENV_VAR}}` 참조만**) → `./harness mcp <harness> --node <node>` → **자격증명은 `.env`(gitignored)에 넣게 안내**(자동 주입, export 아님) |
| "이 데이터 넣어줘/인제스트" | 파일을 `projects/<node>-node/data/update/` 에 두고 `./harness ingest <node>` (원본→archives, 출처→info/index.yaml) |
| "검색/찾아줘" (의미 검색) | MCP `search_info`/`search_all` 또는 `./harness search <node> "<질의>"` |
| "테스트/검증 돌려줘" | `./harness verify <node>` (결과는 자동으로 ONBOARDING 에 반영) |
| "플랫폼 업데이트 받아줘" | `./harness update` (git pull --ff-only + 의존성/훅/규칙 갱신) |
| 위험행동(ssh/scp/push/deploy/삭제) | `platform/policies/approval-gates.md` 게이트 통과 + MCP `request_approval` (사람이 최종 승인) |

> 원칙: **시크릿 값은 `.env`(gitignored)에만**(레지스트리/설정엔 `${{ENV_VAR}}` 이름참조), 기판 변경은 **MCP 쓰기 게이트웨이 또는 정식 명령으로만**,
> 경과·결정은 **worklog/ADR 에 기록**. 이렇게 해야 모든 에이전트가 일관 규칙으로 운영·관리된다.
"""


def _node_body(node_name: str) -> str:
    return f"""# {node_name} — 노드 작업 규칙 (강제)

이 디렉토리는 `{node_name}` 프로젝트의 **AI 운영 노드**다. `repo/`(실제 코드)에는 AI 파일을 두지 않는다.

## 진입 순서 (반드시)
1. `history/ONBOARDING.md` — 현재 상태/활성 티켓/최근 결정/알려진 이슈.
2. `code/coding_convention/`, `code/lint/`, `code/static_analysis/` — 코드 규칙.
3. `scenario/debug.md`, `scenario/test/` — 디버그/테스트 플레이북.
4. `info/`(md/db/vector) + `info/index.yaml` — 사실/데이터와 출처.

## 기록 (반드시)
- 진행 경과: `history/worklog/<티켓>.md` (append-only).
- 비자명 결정: `history/adr/`.
- 데이터 업데이트: `data/update/`에 투입 후 `harness ingest {node_name}`.

플랫폼 전역 규칙은 루트 `AGENTS.md`를 따른다. (재생성: `python tools/gen_agent_rules.py --node {node_name}`)
"""


def _write(base_dir: str, body: str, regen_arg: str):
    """정본 AGENTS.md 1벌 작성 + 활성 하네스(레지스트리)의 진입 파일을 정본으로 심링크."""
    header = HEADER % (__tool_version__, regen_arg)
    out = header + "\n" + body
    written = []
    canon = os.path.join(base_dir, CANONICAL)
    open(canon, "w", encoding="utf-8").write(out)
    written.append((os.path.relpath(canon, ROOT), "정본(git 추적)"))
    for name, cfg in registry.enabled():
        rel = (cfg or {}).get("rules_file")
        if not rel:
            continue
        link = os.path.join(base_dir, rel)
        os.makedirs(os.path.dirname(link) or ".", exist_ok=True)
        if os.path.islink(link) or os.path.exists(link):
            os.remove(link)
        target = os.path.relpath(canon, os.path.dirname(link))   # 예: "AGENTS.md" 또는 "../AGENTS.md"
        try:
            os.symlink(target, link)
            note = "→ %s [%s] (심링크·미추적)" % (target, name)
        except OSError:
            shutil.copyfile(canon, link)
            note = "복제 [%s] (심링크 미지원 OS)" % name
        written.append((os.path.relpath(link, ROOT), note))
    return written


def generate(node: str | None = None):
    print("[gen-rules] 플랫폼 루트:")
    for path, note in _write(ROOT, _platform_body(), ""):
        print("  - %-40s %s" % (path, note))
    if node:
        nd = os.path.join(ROOT, "projects", "%s-node" % node)
        if not os.path.isdir(nd):
            print("[gen-rules] 노드 없음: %s" % nd, file=sys.stderr); return 1
        print("[gen-rules] 노드 %s:" % node)
        for path, note in _write(nd, _node_body(node), " --node %s" % node):
            print("  - %-40s %s" % (path, note))
    return 0


def main():
    ap = argparse.ArgumentParser(description="진입 규칙 파일 생성(강제성 ① 보편층)")
    ap.add_argument("--node", default=None, help="노드 레벨 규칙도 생성(예: my_proj)")
    a = ap.parse_args()
    sys.exit(generate(a.node))


if __name__ == "__main__":
    main()
