#!/usr/bin/env python3
"""gen_agent_rules — 단일 진실원본에서 플랫폼별 '진입 규칙 파일'을 생성.

강제성 ① 보편층(모델·하네스 비종속): 어떤 AI 에이전트(Claude/Cursor/Gemini/Copilot/API)든
자기 하네스가 자동 로드하는 파일을 통해 동일 규칙을 주입받는다.

진실원본: platform/prompts/global-system.md (+ platform/policies/).
정본 1벌만 만들고(추적), 나머지 하네스 파일명은 정본으로의 **심볼릭 링크**(미추적):
  - AGENTS.md                          ← 정본(Codex/Cursor/다수 표준이 직접 읽음). git 에 추적.
  - CLAUDE.md → AGENTS.md               (Claude Code)
  - GEMINI.md → AGENTS.md               (Gemini CLI)
  - .cursorrules → AGENTS.md            (Cursor 레거시)
  - .github/copilot-instructions.md → ../AGENTS.md  (GitHub Copilot)
심링크는 .gitignore 로 미추적 — `harness gen-rules`(또는 `make ready`)가 로컬에서 생성하므로
드리프트가 없고, Windows 등 심링크 미지원 OS에서는 자동으로 복제 폴백한다. 다른 파일명이 필요하면
`ln -s AGENTS.md <필요한이름>`.

사용:
  python tools/gen_agent_rules.py            # 플랫폼 루트
  python tools/gen_agent_rules.py --node project_A   # 노드 레벨
정본은 AUTO-GENERATED 헤더가 붙으며 재생성으로 덮어쓴다(수동 편집 금지).
"""
from __future__ import annotations
import argparse, os, shutil, sys

__tool_version__ = "0.2.0"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # tools/ 의 부모
CANONICAL = "AGENTS.md"                      # 유일 추적 파일(정본)
LINK_NAMES = ["CLAUDE.md", "GEMINI.md", ".cursorrules",
              os.path.join(".github", "copilot-instructions.md")]  # 정본으로의 심링크

HEADER = (
    "<!-- AUTO-GENERATED by tools/gen_agent_rules.py (v%s) — DO NOT EDIT BY HAND.\n"
    "     진실원본: platform/prompts/global-system.md (+ platform/policies/).\n"
    "     재생성: python tools/gen_agent_rules.py%s -->\n"
)


def _global_rules() -> str:
    """global-system.md 본문(헤더 제외 규칙들)을 추출."""
    p = os.path.join(ROOT, "platform", "prompts", "global-system.md")
    if not os.path.exists(p):
        return "(platform/prompts/global-system.md 없음 — 먼저 작성하세요.)"
    lines = open(p, encoding="utf-8").read().splitlines()
    # frontmatter(---...---) 와 첫 H1 제거 후 본문만
    body, in_fm, seen_h1 = [], False, False
    for ln in lines:
        if ln.strip() == "---":
            in_fm = not in_fm; continue
        if in_fm:
            continue
        if not seen_h1 and ln.startswith("# "):
            seen_h1 = True; continue
        body.append(ln)
    return "\n".join(body).strip()


def _platform_body() -> str:
    rules = _global_rules()
    return f"""# ai-autodev-harness — 에이전트 운영 규칙 (강제)

이 저장소는 **모델·하네스 비종속 AI 자동개발 하네스**다. 어떤 AI 에이전트(Claude/Cursor/Gemini/
Copilot/API)든 이 파일을 진입점으로 읽고 아래 규칙을 **반드시** 따른다.
규칙 위반 산출물은 pre-commit / CI 훅(`tools/validate_node.py`)이 거부한다.

> 이 `AGENTS.md`가 **정본**이다. `CLAUDE.md`/`GEMINI.md`/`.cursorrules`/Copilot 파일은 이 파일로의
> 심볼릭 링크이며 git 에 추적하지 않는다(`harness gen-rules`로 생성). 다른 파일명이 필요하면
> `ln -s AGENTS.md <필요한이름>`.

## 0. 이 프로젝트가 무엇인가
- `projects/<name>-node/repo/` = 실제 소프트웨어 코드(symlink/clone/submodule).
- `projects/<name>-node/`(repo 제외) = 그 프로젝트의 **AI 운영 데이터**(context/scenario/history/info/code 규칙).
- 플랫폼 루트 = 글로벌 AI 설정(`platform/`), 변환 도구(`tools/`), 기판 노출(`mcp/`), 어댑터(`adapters/`).
- 사용법: `docs/USAGE.md` · 설계: `docs/ARCHITECTURE.md` · 학습: `docs/learning/harness-curriculum.md`.

## 1. 공통 규칙 (필수)
{rules}

## 2. 파일 배치 (강제)
- `repo/` 안에는 AI 파일(프롬프트/컨텍스트/이력/info)을 **절대** 두지 않는다 — 전부 `-node/` 레벨에.
- 데이터는 `data/update/`에 투입 → `harness ingest <node>`(또는 어댑터의 `/update`)로
  `info/`(md/SQL/vector)로 변환. 원본은 `archives/`, 출처·해시는 `info/index.yaml`.
- 변환기는 `tools/data-to-info/`에 두고 `tools/README.md` 규칙을 따른다.

## 3. 작업 진입 절차
1) 노드 `history/ONBOARDING.md` 읽기 → 2) `code/coding_convention/` 읽기 →
3) plan → verify → implement → 4) 경과를 `history/worklog/<티켓>.md`에 기록 →
5) 위험행동(ssh/scp/push/deploy/삭제)은 `platform/policies/approval-gates.md` 게이트 통과.

## 4. 검증 (커밋 전 필수)
`python tools/validate_node.py <node>` 통과해야 한다(pre-commit 훅이 자동 실행, CI에서도 검사).
직접 파일쓰기는 허용되나, 규칙 위반은 훅이 사후 거부한다.
"""


def _node_body(node_name: str) -> str:
    return f"""# {node_name} — 노드 작업 규칙 (강제)

이 디렉토리는 `{node_name}` 프로젝트의 **AI 운영 노드**다. `repo/`(실제 코드)에는 AI 파일을 두지 않는다.

## 진입 순서 (반드시)
1. `history/ONBOARDING.md` — 현재 상태/활성 티켓/최근 결정/알려진 이슈.
2. `code/coding_convention/`, `code/lint/`, `code/static_analysis/` — 코드 규칙.
3. `scenario/debug.md`, `scenario/test/` — 디버그/테스트 플레이북.
4. `info/`(md/db/vector) + `info/index.yaml` — 사실/데이터와 출처.

## 기록 (반드시)
- 진행 경과: `history/worklog/<티켓>.md` (append-only).
- 비자명 결정: `history/adr/`.
- 데이터 업데이트: `data/update/`에 투입 후 `harness ingest {node_name}`.

플랫폼 전역 규칙은 루트 `AGENTS.md`/`CLAUDE.md`를 따른다. (재생성: `python tools/gen_agent_rules.py --node {node_name}`)
"""


def _write(base_dir: str, body: str, regen_arg: str):
    """정본 AGENTS.md 1벌 작성 + 나머지 하네스 파일명을 정본으로 심링크(미지원 OS면 복제)."""
    header = HEADER % (__tool_version__, regen_arg)
    out = header + "\n" + body
    written = []
    canon = os.path.join(base_dir, CANONICAL)
    open(canon, "w", encoding="utf-8").write(out)
    written.append((os.path.relpath(canon, ROOT), "정본(git 추적)"))
    for rel in LINK_NAMES:
        link = os.path.join(base_dir, rel)
        os.makedirs(os.path.dirname(link) or ".", exist_ok=True)
        if os.path.islink(link) or os.path.exists(link):
            os.remove(link)
        target = os.path.relpath(canon, os.path.dirname(link))   # 예: "AGENTS.md" 또는 "../AGENTS.md"
        try:
            os.symlink(target, link)
            note = "→ %s (심링크·미추적)" % target
        except OSError:
            shutil.copyfile(canon, link)
            note = "복제(심링크 미지원 OS)"
        written.append((os.path.relpath(link, ROOT), note))
    return written


def generate(node: str | None = None):
    print("[gen-rules] 플랫폼 루트:")
    for path, note in _write(ROOT, _platform_body(), ""):
        print("  - %-40s %s" % (path, note))
    if node:
        nd = os.path.join(ROOT, "projects", "%s-node" % node)
        if not os.path.isdir(nd):
            print("[gen-rules] 노드 없음: %s" % nd, file=sys.stderr); return 1
        print("[gen-rules] 노드 %s:" % node)
        for path, note in _write(nd, _node_body(node), " --node %s" % node):
            print("  - %-40s %s" % (path, note))
    return 0


def main():
    ap = argparse.ArgumentParser(description="진입 규칙 파일 생성(강제성 ① 보편층)")
    ap.add_argument("--node", default=None, help="노드 레벨 규칙도 생성(예: project_A)")
    a = ap.parse_args()
    sys.exit(generate(a.node))


if __name__ == "__main__":
    main()
